# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: Ms. Karen's Place
description: The hair salon for children
baseurl: "" # the subpath of your site, e.g. /blog
url: https://mskarensplace.com # the base hostname & protocol for your site, e.g. http://example.com
email: karengaskins@sbcglobal.net
facebook_link: https://www.facebook.com/Ms-Karens-Place-103902163035918/
phone: 9252832855
location: https://www.google.com/maps/place/Ms+Karen's+Place/@37.8915904,-122.1231474,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x33428884dd8584!8m2!3d37.8915904!4d-122.1209587
rss: news/atom.xml

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  path: news/atom.xml

permalink: pretty
permalink: /:title/

collections:
  people:
    output: true
  news:
    output: true

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "people"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: news/:title
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - _classes/TEMPLATE-classes.md
  - _people/TEMPLATE-people.md
  - assets
  - Gemfile
  - Gemfile.lock
